[pytest]


addopts = --strict-markers
markers =
    smoke: tests that can be executed quickly
    regression: for regression tests
    positive: for positive tests
    negative: for negative tests
    custom_mark_my_own: custom test for my own
    class_tests: tests in class object
    convert_time: test with time converting function
    swapi: test for swapi endpoints
    gorest: test for gorest endpoints
    gorest_23: test for gorest endpoints from lesson 23
    ui: test UI

log_cli = true
log_cli_level = INFO
log_cli_format = (levelname) %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S



